name: jasbe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11
  fluttertoast: ^8.2.1
  google_fonts: ^4.0.4
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.2.1
  flutter_iconly: ^1.0.2
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  coupon_uikit: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/app/
    - assets/logo/
